# Generated by Django 2.2.1 on 2019-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
