# Generated by Django 2.2.1 on 2019-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='problem',
            field=models.CharField(choices=[('repair', 'Repair Instrument'), ('create', 'Create New Instrument')], default='repair', max_length=254),
        ),
    ]
